import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { Infer, v } from "convex/values";

export const ROLES = { ADMIN: "admin", USER: "user", MEMBER: "member" } as const;
export const SHOP_ROLES = { OWNER: "owner", MANAGER: "manager", ADVISOR: "advisor", TECHNICIAN: "technician", PARTS: "parts", FRONT_DESK: "front_desk", VIEWER: "viewer" } as const;
export const roleValidator = v.union(v.literal(ROLES.ADMIN), v.literal(ROLES.USER), v.literal(ROLES.MEMBER));
export const shopRoleValidator = v.union(v.literal(SHOP_ROLES.OWNER), v.literal(SHOP_ROLES.MANAGER), v.literal(SHOP_ROLES.ADVISOR), v.literal(SHOP_ROLES.TECHNICIAN), v.literal(SHOP_ROLES.PARTS), v.literal(SHOP_ROLES.FRONT_DESK), v.literal(SHOP_ROLES.VIEWER));
export type Role = Infer<typeof roleValidator>;
export type ShopRole = Infer<typeof shopRoleValidator>;
export const evidenceLevels = v.union(v.literal("verified_fact"), v.literal("strong_evidence"), v.literal("professional_inference"), v.literal("unknown"));
export type EvidenceLevel = Infer<typeof evidenceLevels>;
const orgId = v.id("organizations");

const schema = defineSchema({
  ...authTables,
  users: defineTable({ name: v.optional(v.string()), image: v.optional(v.string()), email: v.optional(v.string()), emailVerificationTime: v.optional(v.number()), isAnonymous: v.optional(v.boolean()), role: v.optional(roleValidator) }).index("email", ["email"]),
  organizations: defineTable({ name: v.string(), type: v.union(v.literal("shop"), v.literal("dealership"), v.literal("fleet"), v.literal("individual")), ownerId: v.id("users"), status: v.union(v.literal("active"), v.literal("suspended"), v.literal("archived")), createdAt: v.number(), updatedAt: v.number() }).index("by_owner", ["ownerId"]).index("by_status", ["status"]),
  organizationMembers: defineTable({ organizationId: orgId, userId: v.id("users"), role: shopRoleValidator, status: v.union(v.literal("active"), v.literal("invited"), v.literal("suspended")), createdAt: v.number(), updatedAt: v.number() }).index("by_org", ["organizationId"]).index("by_user", ["userId"]).index("by_org_user", ["organizationId", "userId"]),
  locations: defineTable({ organizationId: orgId, name: v.string(), address: v.optional(v.string()), phone: v.optional(v.string()), timezone: v.string(), status: v.union(v.literal("active"), v.literal("inactive")), createdAt: v.number() }).index("by_org", ["organizationId"]),
  customers: defineTable({ organizationId: orgId, locationId: v.optional(v.id("locations")), name: v.string(), email: v.optional(v.string()), phone: v.optional(v.string()), notes: v.optional(v.string()), status: v.union(v.literal("active"), v.literal("archived")), createdAt: v.number(), updatedAt: v.number() }).index("by_org", ["organizationId"]).index("by_org_email", ["organizationId", "email"]),
  vehicles: defineTable({ organizationId: orgId, customerId: v.optional(v.id("customers")), fleetId: v.optional(v.id("fleets")), vin: v.optional(v.string()), year: v.optional(v.number()), make: v.optional(v.string()), model: v.optional(v.string()), trim: v.optional(v.string()), odometerKm: v.optional(v.number()), identityConfidence: v.union(v.literal("verified"), v.literal("user_supplied"), v.literal("unknown")), status: v.union(v.literal("active"), v.literal("archived")), createdAt: v.number(), updatedAt: v.number() }).index("by_org", ["organizationId"]).index("by_org_vin", ["organizationId", "vin"]).index("by_customer", ["customerId"]),
  fleets: defineTable({ organizationId: orgId, name: v.string(), managerId: v.optional(v.id("users")), status: v.union(v.literal("active"), v.literal("archived")), createdAt: v.number(), updatedAt: v.number() }).index("by_org", ["organizationId"]),
  appointments: defineTable({ organizationId: orgId, locationId: v.optional(v.id("locations")), customerId: v.id("customers"), vehicleId: v.optional(v.id("vehicles")), assignedUserId: v.optional(v.id("users")), startAt: v.number(), endAt: v.number(), serviceType: v.string(), notes: v.optional(v.string()), status: v.union(v.literal("requested"), v.literal("confirmed"), v.literal("checked_in"), v.literal("completed"), v.literal("cancelled"), v.literal("no_show")), createdAt: v.number(), updatedAt: v.number() }).index("by_org_start", ["organizationId", "startAt"]).index("by_customer", ["customerId"]),
  repairOrders: defineTable({ organizationId: orgId, locationId: v.optional(v.id("locations")), customerId: v.id("customers"), vehicleId: v.id("vehicles"), appointmentId: v.optional(v.id("appointments")), advisorId: v.optional(v.id("users")), technicianId: v.optional(v.id("users")), number: v.string(), status: v.union(v.literal("draft"), v.literal("estimate"), v.literal("authorized"), v.literal("in_progress"), v.literal("awaiting_parts"), v.literal("quality_check"), v.literal("ready"), v.literal("closed"), v.literal("cancelled")), concern: v.string(), verifiedEvidence: v.optional(v.array(v.string())), customerAuthorizationAt: v.optional(v.number()), totalsCents: v.object({ labor: v.number(), parts: v.number(), fees: v.number(), tax: v.number(), total: v.number() }), createdAt: v.number(), updatedAt: v.number() }).index("by_org", ["organizationId"]).index("by_org_number", ["organizationId", "number"]).index("by_vehicle", ["vehicleId"]),
  workOrderItems: defineTable({ organizationId: orgId, repairOrderId: v.id("repairOrders"), kind: v.union(v.literal("labor"), v.literal("part"), v.literal("sublet"), v.literal("fee")), description: v.string(), quantity: v.number(), unitPriceCents: v.number(), status: v.union(v.literal("proposed"), v.literal("authorized"), v.literal("completed"), v.literal("declined")), evidenceRef: v.optional(v.string()), createdAt: v.number() }).index("by_ro", ["repairOrderId"]),
  invoices: defineTable({ organizationId: orgId, repairOrderId: v.id("repairOrders"), number: v.string(), status: v.union(v.literal("draft"), v.literal("issued"), v.literal("paid"), v.literal("void"), v.literal("refunded")), totalCents: v.number(), currency: v.string(), issuedAt: v.optional(v.number()), paidAt: v.optional(v.number()), createdAt: v.number() }).index("by_org", ["organizationId"]).index("by_ro", ["repairOrderId"]),
  diagnosticSessions: defineTable({ userId: v.id("users"), organizationId: v.optional(orgId), title: v.string(), vehicleInfo: v.optional(v.object({ make: v.optional(v.string()), model: v.optional(v.string()), year: v.optional(v.number()), vin: v.optional(v.string()) })), status: v.union(v.literal("active"), v.literal("resolved"), v.literal("archived")), confidenceSummary: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() }).index("by_user", ["userId"]).index("by_user_status", ["userId", "status"]).index("by_org", ["organizationId"]),
  diagnosticMessages: defineTable({ sessionId: v.id("diagnosticSessions"), role: v.union(v.literal("user"), v.literal("assistant"), v.literal("system")), content: v.string(), evidence: v.optional(v.object({ level: evidenceLevels, sources: v.array(v.object({ type: v.string(), reference: v.string(), url: v.optional(v.string()) })), confidence: v.optional(v.number()), missingEvidence: v.optional(v.array(v.string())), alternativeExplanations: v.optional(v.array(v.string())), nextStep: v.optional(v.string()), safetyFlags: v.optional(v.array(v.string())) })), attachments: v.optional(v.array(v.object({ type: v.union(v.literal("image"), v.literal("audio")), name: v.string(), storageId: v.optional(v.string()), transcript: v.optional(v.string()) }))), createdAt: v.number() }).index("by_session", ["sessionId"]),
  rateLimits: defineTable({ userId: v.id("users"), window: v.string(), count: v.number() }).index("by_user_window", ["userId", "window"]),
  auditLogs: defineTable({ userId: v.id("users"), action: v.union(v.literal("session_create"), v.literal("session_delete"), v.literal("message_send"), v.literal("ai_request")), targetId: v.string(), metadata: v.optional(v.any()), timestamp: v.number() }).index("by_user", ["userId"]).index("by_action", ["action"]),
  uploadClaims: defineTable({ userId: v.id("users"), tokenHash: v.string(), storageId: v.optional(v.string()), contentType: v.string(), fileName: v.string(), createdAt: v.number(), expiresAt: v.number(), claimedAt: v.optional(v.number()) }).index("by_token", ["tokenHash"]).index("by_user", ["userId"]).index("by_user_storage", ["userId", "storageId"]),
}, { schemaValidation: true });

export default schema;
